# overall CI pipeline name
name: Build and test export server

# only run on master and stage branches
on:
  push:
    branches:
    - master
    - stage

# Environment variables available to all jobs and steps in this workflow
env:
  CI: true
    
# jobs are the different pipelines
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # define all the steps in the "build" stage
    steps:
    # use the checkout action
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Try to build and run tests again export server
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test

