# overall CI pipeline name
name: Build and test export server

# Run tests on EVERY branch and push
on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  CI: true
    
# jobs are the different pipelines
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    # define all the steps in the "build" stage
    steps:
    # use the checkout action to get repository contents
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Try to build and run tests again export server
    - name: Run Tests
      run: |
        npm ci
        npm test

