# overall CI pipeline name
name: Deploy to GAE

# only run on master and stage branches
on:
  push:
    branches:
    - master
    - stage

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
  APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    
# jobs are the different pipelines
jobs:
  build:

    runs-on: ubuntu-latest
    name: Publish and Deploy
    # define all the steps in the "build" stage
    steps:
    # Configure where to deploy export server
    - name: Deploy Stage
      uses: actions-hub/gcloud@master
      if: github.ref == 'refs/heads/stage'
      run: |
        gcloud app deploy --version stage
    - name: Deploy Production
      uses: actions-hub/gcloud@master
      if: github.ref == 'refs/heads/master'
      run: |
        gcloud app deploy