# overall CI pipeline name
name: Deploy to GAE

# only run on master and stage branches
on:
  push:
    branches:
    - master
    - stage

# Environment variables available to all jobs and steps in this workflow
env:
  # Project id
  PROJECT_ID: export-server
  # GCP authorization credentials
  APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
  # define to use gcloud over gsutil
  CLI: gcloud

# jobs are the different pipelines
jobs:
  build:

    # Define the OS and name
    runs-on: ubuntu-latest
    name: Publish and Deploy

    # define all the steps in the "build" stage
    steps:
    # This step checks out a copy of your repository.
    - uses: actions/checkout@v1
    # This step checks out and logs in to gcloud
    - name: Deploy Stage
      if: github.ref == 'refs/heads/stage'
      uses: actions-hub/gcloud@master
      with:
        # This step deploys to stage and the --no-promote flag prevents
        # traffic from being split to this version
        args: app deploy app-stage.yaml --version stage 
    # This step checks out and logs in to gcloud
    - name: Deploy Production
      if: github.ref == 'refs/heads/master'
      uses: actions-hub/gcloud@master
      with:
        # This step deploys to production
        args: app deploy app.yaml --version master