# overall CI pipeline name
name: Deploy to GAE

# only run on master and stage branches
on:
  push:
    branches:
    - master
    - stage

# Environment variables available to all jobs and steps in this workflow
# env:
#   PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
#   APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    
# jobs are the different pipelines
jobs:
  build:

    runs-on: ubuntu-latest
    name: Publish and Deploy
    # define all the steps in the "build" stage
    steps:
    # This step checks out a copy of your repository.
    - uses: actions/checkout@v1
    # This step checks out and logs in to gcloud
    - uses: actions-hub/gcloud@master
      env:
        # Project id
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        # GCP authorization credentials
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        # define to use gcloud over gsutil
        CLI: gcloud
      with:
        args: app deploy app-stage.yaml
    # Configure where to deploy export server
    - name: Deploy Stage
      if: github.ref == 'refs/heads/stage'
      run: |
        gcloud app deploy --version stage
    - name: Deploy Production
      if: github.ref == 'refs/heads/master'
      run: |
        gcloud app deploy